# Generated by Django 4.0.7 on 2023-03-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
